[package]
name = "chapter03"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chapter02.workspace = true
tiktoken.workspace = true

[dependencies.burn]
features = ["autodiff", "ndarray"]
workspace = true
