[package]
name = "chapter02"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
regex.workspace = true
tch.workspace = true
tiktoken.workspace = true

[dependencies.reqwest]
features = ["blocking"]
workspace = true
