[package]
name = "chapter04"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chapter03.workspace = true
plotters = "=0.3"
tiktoken.workspace = true

[dependencies.burn]
features = ["autodiff", "ndarray"]
workspace = true
